version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.1

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    build: ./
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    container_name: webui
    hostname: webui
    ports:
      - "3100:3000"
    volumes:
        - "./config:/etc/open5gs"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_webui.sh"
    networks:
      core_network:
        ipv4_address: 192.168.26.6

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=mongodb
    container_name: "dbprovisioner"
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      core_network:
        ipv4_address: 192.168.26.19

  hss:
    build: ./
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_hss.sh"
    volumes:
      - "./config:/etc/open5gs"
    networks:
      core_network:
        ipv4_address: 192.168.26.10

  mme:
     build: ./
     depends_on:
       - hss
     container_name: mme
     hostname: mme
     entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_mme.sh"
     volumes:
      - "./config:/etc/open5gs"
     networks:
       core_network:
         ipv4_address: 192.168.26.20

  sgw:
     build: ./
     container_name: sgw
     hostname: sgw
     entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_sgw.sh"
     volumes:
      - "./config:/etc/open5gs"
     networks:
       core_network:
         ipv4_address: 192.168.26.30

  pgw:
     build: ./
     restart: always
     container_name: pgw
     hostname: pgw
     privileged: true
     entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pgw.sh"
     volumes:
      - "./config:/etc/open5gs"
     cap_add:
       -  NET_ADMIN
     devices:
       -  /dev/net/tun
     networks:
       core_network:
         ipv4_address: 192.168.26.40

  pcrf:
    build: ./
    depends_on:
       - mongodb
       - hss
    container_name: pcrf
    hostname: pcrf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pcrf.sh"
    volumes:
      - "./config:/etc/open5gs"
    networks:
       core_network:
         ipv4_address: 192.168.26.50
