version: '3'

networks:
  s1c:
    external: true
  s1u:
    external: true
  db:
   ipam:
     driver: default 
     config:
      - subnet: 192.168.50.0/24


services:
  mongodb:
    image: mongo:latest
    container_name: "open5gs_mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      db:
        ipv4_address: 192.168.50.10
  
  webui:
    build: ./webui
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/open5gs
      - MONGODB_STARTUP_TIME=15
    container_name: "open5gs_webui"
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
        - "./config-allinone:/etc/open5gs"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/webui.sh"
    networks:
      db:
        ipv4_address: 192.168.50.11
  
  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=mongodb
    container_name: "open5gs_dbloader"
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      db:
        ipv4_address: 192.168.50.12

  epc:
    depends_on:
      - mongodb
    container_name: "open5gs_epc"
    build:
      context: ./
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./config-allinone:/etc/open5gs
    networks:
       db: 
         ipv4_address: 192.168.50.2
       s1c:
         ipv4_address: 10.15.16.2
       s1u:
         ipv4_address: 10.15.17.2
    hostname: open5gs-run
    command: /bin/bash -c "/etc/open5gs/setup.sh; /bin/open5gs-pcrfd -D; /bin/open5gs-pgwd -D; /bin/open5gs-sgwd -D; /bin/open5gs-hssd -D; /bin/open5gs-mmed"
    
volumes:
  mongodb_data: