---
- hosts: all
  become: true
  tasks:
  - name: Install docker.io
    apt: name="docker.io" state=present update_cache=yes

  - name: Install docker-compose
    apt: name="docker-compose" state=present

  - name: adding existing user to group docker
    user:
      name: '{{ ansible_user }}'
      groups: docker
      append: yes

 - name: build the containers
   docker_image:
     build:
       path: ./
     name: epc_image
     source: build
           
