---
- hosts: all
  become: true
  tasks:
  - name: Install docker.io
    apt: name="docker.io" state=present update_cache=yes

  - name: Install docker-compose
    apt: name="docker-compose" state=present

  - name: adding existing user to group docker
    user:
      name: '{{ ansible_user }}'
      groups: docker
      append: yes

  - name: build and run `docker-compose up`
    docker_compose:
      files: docker-compose-allinone-pcloud.yml
      build: yes
    register: output

  - debug:
      var: output

  - assert:
      that:
        - "mongodb.open5gs_mongodb.state.running"
        - "webui.open5gs_webui.state.running"
        - "epc.open5gs_epc.state.running"
