---
- hosts: all
  become: true
  tasks:
  - name: Install docker.io
    apt:
      name: "docker.io"
      state: latest
      update_cache: yes

  - name: adding existing user '{{ user }}' to group docker
    user:
      name: '{{ ansible_user }}'
      groups: docker
      append: yes

  - name: enable docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install docker-compose
    apt: name="docker-compose" state=present

  - name: build
    docker_compose:
      project_src: dissag-cfg/config-diss-cpf/
      build: yes
      state: "present"
    register: output

  - debug:
      var: output
