version: '3'

volumes:
 mongodb_data:

services:
  mongodb:
    image: mongo:latest
    container_name: "open5gs_mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: "mongodb"
    restart: "always"
    network_mode: "host"

  webui:
    build:
      context: ./webui
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://127.0.0.1/open5gs
      - MONGODB_STARTUP_TIME=15
    container_name: "open5gs_webui"
    hostname: "webui"
    restart: "always"
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      - "./cfg:/etc/open5gs:z"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_webui.sh"

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=127.0.0.1
      - MONGODB_STARTUP_TIME=25
    network_mode: "host"
    container_name: "open5gs_dbprovisioner"
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh:z"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json:z"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh

  hss:
    build:
      context: ../../
    depends_on:
      - mongodb
    container_name: "open5gs_hss"
    hostname: "hss"
    network_mode: "host"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_hss.sh"
    volumes:
      - "./cfg:/etc/open5gs:z"

  mme:
    build:
      context: ../../
    depends_on:
      - hss
    container_name: "open5gs_mme"
    hostname: "mme"
    network_mode: "host"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_mme.sh"
    volumes:
      - "./cfg:/etc/open5gs:z"
