apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp9s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.50.0/24",
        "rangeStart": "192.168.50.20",
        "rangeEnd": "192.168.50.23",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.50.1"
      },
      "dns": {
        "nameservers" : ["192.168.50.1"],
        "search" : ["home"]
      }
    }'
