version: '3'

networks:
  physical:
    external: true
services:

  sgw:
    build:
      context: ../../
    container_name: "open5gs_sgw"
    hostname: "sgw"
    restart: "always"
    networks:
      physical:
        ipv4_address: 172.30.2.12
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_sgw.sh"
    volumes:
      - "./cfg:/etc/open5gs:z"

  pgw:
    build:
      context: ../../
    container_name: "open5gs_pgw"
    hostname: "pgw"
    privileged: true
    restart: "always"
    networks:
      physical:
        ipv4_address: 172.30.2.13
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pgw.sh"
    volumes:
      - "./cfg:/etc/open5gs:z"
    cap_add:
      -  NET_ADMIN
    devices:
      -  /dev/net/tun

  pcrf:
    build:
      context: ../../
    container_name: "open5gs_pcrf"
    hostname: "pcrf"
    networks:
      physical:
        ipv4_address: 172.30.2.14
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pcrf.sh"
    volumes:
      - "./cfg:/etc/open5gs:z"
    restart: "always"
