apiVersion: v1
kind: Service
metadata:
  name: udplistener
spec:
  ports:
    - protocol: UDP
      port: 5005
      targetPort: 5005
      nodePort: 5005
  selector:
    app: udplistener
  type: LoadBalancer

